version: "3.5"
# Features driving version requirement
# - networks.name                 3.5
# - healthcheck.start_period      2.3
# - healthcheck                   2.1

services:
  # Apollo: combines the hasura and graphql schemas into a unified schema, the primary API entrypoint
  apollo:
    image: hoangperry/prefect-apollo:lastest
    ports:
      - "4200:4200"
    command: bash -c "./post-start.sh && npm run serve"
    environment:
      HASURA_API_URL: http://14.241.231.87:3000/v1alpha1/graphql
      PREFECT_API_URL: http://14.241.231.87:4201/graphql/
      PREFECT_API_HEALTH_URL: http://14.241.231.87:4201/health
      PREFECT_SERVER__TELEMETRY__ENABLED: ${PREFECT_SERVER__TELEMETRY__ENABLED:-true}
      GRAPHQL_SERVICE_HOST: http://14.241.231.87
      GRAPHQL_SERVICE_PORT: 4201
    healthcheck:
      test: curl --fail --silent "http://localhost:4200/.well-known/apollo/server-health" &> /dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
